version: '3.8'

services:
  web:
    image: an1medani/animeshop:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/product
    depends_on:
      - db
    networks:
      - network
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - network

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/product
      # - ./nginx/ssl:/nginx/ssl
    depends_on:
      - web
    networks:
      - network

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  network:
